export enum ReservationStatusEnum {
  PENDING = 'PENDING',
  WAITING_SLIP = 'WAITING_SLIP',
  SLIP_UPLOADED = 'SLIP_UPLOADED',
  SLIP_VERIFIED = 'SLIP_VERIFIED',
  CHECK_IN = 'CHECK_IN',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
}
